version: 0.2

phases:
  install:
    commands:
      - echo "Updating system packages and installing dependencies..."
      - yum update -y
      - yum install -y git docker
      - yum install -y jq

  pre_build:
    commands:
      - echo "Cloning the repository from GitHub..."
      - git clone https://github.com/mohanish619/frontendcodebuild.git
      - cd frontendcodebuild
      - echo "Setting up environment variables..."
      - echo "VITE_API_URL=/api" > .env
      - echo "Authenticating with Docker Hub..."
      - export DOCKER_USERNAME=$(aws secretsmanager get-secret-value --secret-id docker-hub-credentials --query SecretString --output text | jq -r .username)
      - export DOCKER_PASSWORD=$(aws secretsmanager get-secret-value --secret-id docker-hub-credentials --query SecretString --output text | jq -r .password)
      - echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME --password-stdin
      - echo "Docker Hub authentication successful."
  
  build:
    commands:
      - echo "Building a Docker image for the application..."
      - docker build -t my-frontend-app .
      - echo "Docker image built successfully."
  
  post_build:
    commands:
      - echo "Tagging and pushing the Docker image to the registry..."
      - docker tag my-frontend-app 156041427059.dkr.ecr.us-east-2.amazonaws.com/my-frontend-app:latest
      - docker push 156041427059.dkr.ecr.us-east-2.amazonaws.com/my-frontend-app:latest
      - echo "Docker image pushed successfully."

artifacts:
  files:
    - "**/*"
  discard-paths: yes
