# Use an official Node.js image as the base
FROM node:18

# Install system dependencies using yum
RUN yum update -y && yum install -y \
    git \
    nginx \
    && yum clean all

# Install NVM
RUN curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash && \
    export NVM_DIR="$HOME/.nvm" && \
    [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh" && \
    nvm install --lts

# Set working directory
WORKDIR /app

# Copy necessary files for nginx configuration
COPY . /app

# Copy nginx.conf template
COPY nginx.conf /etc/nginx/nginx.conf

# Expose port 80 for nginx
EXPOSE 80

# Default command to start nginx
CMD ["nginx", "-g", "daemon off;"]
